apiVersion: apps/v1
kind: Deployment
metadata:
  name: yaml-validator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: yaml-validator
  template:
    metadata:
      labels:
        app: yaml-validator
    spec:
      containers:
        - name: yaml-validator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8003
