apiVersion: v1
kind: Service
metadata:
  name: yaml-validator
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8003
  selector:
    app: yaml-validator
